### ISSUE TITLE
Flashing Klipper to Toolhead fails as script cannot connect to bootloader

### ISSUE THREAD

**Issue by deveth0** [frap129/OpenQ1#23]
Hi, 

I closely followed your instructions and was able to build katapult and mount the toolhead.

In Part 4 - 4. - x. you unmount the toolhead and then flash klipper using python3, I was not able to connect to it.

What worked for me: remove the USB cable, plugin original the connector and then press reset on the toolhead twice (quite fast). 

This was the error:
```
mks@qidi-q1:~/katapult$ sudo python3 scripts/flashtool.py -d /dev/ttyS2 -f ~/klipper/out/klipper.bin
Attempting to connect to bootloader
ERROR:root:Flash Error
Traceback (most recent call last):
  File "/home/mks/katapult/scripts/flashtool.py", line 554, in run
    await flasher.connect_btl()
  File "/home/mks/katapult/scripts/flashtool.py", line 90, in connect_btl
    ret = await self.send_command('CONNECT')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mks/katapult/scripts/flashtool.py", line 196, in send_command
    raise FlashCanError("Error sending command [%s] to Can Device"
FlashCanError: Error sending command [CONNECT] to Can Device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mks/katapult/scripts/flashtool.py", line 633, in main
    loop.run_until_complete(sock.run(args.device, args.baud, fpath))
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/mks/katapult/scripts/flashtool.py", line 561, in run
    await flasher.finish()
  File "/home/mks/katapult/scripts/flashtool.py", line 275, in finish
    await self.send_command("COMPLETE")
  File "/home/mks/katapult/scripts/flashtool.py", line 196, in send_command
    raise FlashCanError("Error sending command [%s] to Can Device"
FlashCanError: Error sending command [COMPLETE] to Can Device
```

**Comment by frap129** [comment]
This could be caused by klipper hogging the device. You can stop klipper by running `sudo systemctl stop klipper`, then try to flash, and finally restart klipper with `sudo systemctl start klipper`

**Comment by deveth0** [comment]
can*t try that anymore as I already were able to get the device flashed, but probably helpful for others. Thx for commenting

**Comment by not-purple** [comment]
Hi, I have the same problem. And I can confirm `sudo systemctl restart klipper` fixes the issue. Might want to update the Installation Guide for helping others


Here the following log.
`mks@qidi-q1:~/katapult$ mks@qidi-q1:~/katapult$ python3 scripts/flashtool.py -d /dev/ttyS2 -f ~/klipper/out/klipper.bin
ERROR:root:Flash Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 385, in _reconfigure_port
    fcntl.flock(self.fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mks/katapult/scripts/flashtool.py", line 547, in run
    serial_dev.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 332, in open
    self._reconfigure_port(force_update=True)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 387, in _reconfigure_port
    raise SerialException(msg.errno, "Could not exclusively lock port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 11] Could not exclusively lock port /dev/ttyS2: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mks/katapult/scripts/flashtool.py", line 633, in main
    loop.run_until_complete(sock.run(args.device, args.baud, fpath))
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/mks/katapult/scripts/flashtool.py", line 549, in run
    raise FlashCanError("Unable to open serial port: %s" % (e,))
FlashCanError: Unable to open serial port: [Errno 11] Could not exclusively lock port /dev/ttyS2: [Errno 11] Resource temporarily unavailable
mks@qidi-q1:~/katapult$ sudo systemctl restart klipper
mks@qidi-q1:~/katapult$ python3 scripts/flashtool.py -d /dev/ttyS2 -f ~/klipper/out/klipper.bin
Attempting to connect to bootloader
Katapult Connected
Protocol Version: 1.0.0
Block Size: 64 bytes
Application Start: 0x10004000
MCU type: rp2040
Flashing '/home/mks/klipper/out/klipper.bin'...

[##################################################]

Write complete: 141 pages
Verifying (block count = 563)...

[##################################################]

Verification Complete: SHA = A13BEFC43E3755445737E1BC176B4F4D2AE9C3BE
Flash Success
`

**Comment by igorir3** [comment]
I do everything exactly according to the instructions, but the error remains at this step! The klipper is definitely stopped and the cable is intact (I was able to somehow use mount and copy the files)
